"""Render docs/compatibility.md's server matrix from the committed results.

The section between the markers is generated, never edited: a compatibility
claim that can be typed by hand is one that drifts from the evidence. `render`
rewrites it; `check` (run by the unit suite) fails when it differs from what
the results say, and when a published result carries an untriaged failure.
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path
from typing import Any

from conformance.results import latest_per_server
from conformance.runtime import ROOT
from conformance.scenarios import GROUPS, SCENARIOS

DOC = ROOT / "docs" / "compatibility.md"
BEGIN = (
    "<!-- conformance-matrix:begin (generated by `python -m conformance render`; do not edit) -->"
)
END = "<!-- conformance-matrix:end -->"
ISSUES = "https://github.com/IndustriAgents/OPCUA-MCP/issues"

GROUP_OF = {s.id: s.group for s in SCENARIOS}
TITLE_OF = {s.id: s.title for s in SCENARIOS}

LIMITATIONS = ("library-limitation", "server-limitation")
LABELS = {
    "pass": "pass",
    "project-bug": "project bug",
    "library-limitation": "library limitation",
    "server-limitation": "server limitation",
    "unsupported-optional": "unsupported optional feature",
    "not-configured": "not configured",
    "untriaged-failure": "untriaged failure",
}


def support_level(document: dict[str, Any]) -> str:
    """Supported, partially supported — see docs/compatibility.md for the rule."""
    outcomes = {s["outcome"] for run in document["runs"] for s in run["scenarios"]}
    runtimes = {run["runtime"] for run in document["runs"]}
    if runtimes != {"python", "node"} or "untriaged-failure" in outcomes:
        return "Unverified"
    if outcomes & {"project-bug", *LIMITATIONS}:
        return "Partially supported"
    return "Supported"


def _cell(scenarios: list[dict[str, Any]]) -> str:
    """One group for one runtime: how many of the scenarios that ran, passed."""
    counts = Counter(s["outcome"] for s in scenarios)
    ran = sum(counts.values()) - counts["not-configured"]
    if ran == 0:
        return "not configured"
    if counts["unsupported-optional"] == ran:
        return "unsupported"
    applicable = ran - counts["unsupported-optional"]
    text = f"{counts['pass']}/{applicable}"
    if counts["project-bug"]:
        text += " (bug)"
    elif counts["library-limitation"] or counts["server-limitation"]:
        text += " (limited)"
    elif counts["untriaged-failure"]:
        text += " (untriaged)"
    if counts["unsupported-optional"]:
        text += f", {counts['unsupported-optional']} unsupported"
    return text


def _by_group(run: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {g: [] for g in GROUPS}
    for scenario in run["scenarios"]:
        groups[GROUP_OF[scenario["id"]]].append(scenario)
    return groups


def _server_label(document: dict[str, Any]) -> str:
    server = document["server"]
    build = server.get("build_info") or {}
    product = build.get("product_name") or server["name"]
    version = build.get("software_version") or "?"
    return f"{product} {version}"


def _link(tracking: str) -> str:
    """`#171` as a link: a Markdown file on GitHub does not autolink issue numbers."""
    if re.fullmatch(r"#\d+", tracking or ""):
        return f"[{tracking}]({ISSUES}/{tracking[1:]})"
    return tracking or ""


def _findings(document: dict[str, Any]) -> list[str]:
    """One server's failures, once per scenario, saying which runtimes had them.

    The same failure on both runtimes is one row, not two: most findings are in
    code the runtimes share by design, and "both" is itself the information.
    Unsupported features are listed in a sentence — they are the server's
    answer, not a finding — and a scenario the runtimes disagree on is called
    out, because that is a divergence ADR 0001 does not allow.
    """
    by_scenario: dict[str, dict[str, dict[str, Any]]] = {}
    for run in document["runs"]:
        for scenario in run["scenarios"]:
            by_scenario.setdefault(scenario["id"], {})[run["runtime"]] = scenario
    runtimes = sorted(run["runtime"] for run in document["runs"])

    rows, unsupported, disagreements = [], [], []
    for scenario_id in (s.id for s in SCENARIOS):
        results = by_scenario.get(scenario_id, {})
        outcomes = {r["outcome"] for r in results.values()}
        if len(outcomes) > 1:
            disagreements.append(scenario_id)
        if outcomes == {"unsupported-optional"}:
            unsupported.append(scenario_id)
        failing = {
            runtime: r
            for runtime, r in results.items()
            if r["outcome"] not in ("pass", "not-configured", "unsupported-optional")
        }
        # Identical outcome and reason on every runtime collapse to one row.
        groups: dict[tuple[str, str, str], list[str]] = {}
        for runtime, r in sorted(failing.items()):
            triage = r.get("triage", {})
            why = (triage.get("summary") or r.get("detail", "")).replace("|", "/")
            tracking = _link(triage.get("tracking", ""))
            groups.setdefault((r["outcome"], why, tracking), []).append(runtime)
        for (outcome, why, tracking), which in groups.items():
            label = "both" if which == runtimes and len(runtimes) > 1 else ", ".join(which)
            rows.append(f"| `{scenario_id}` | {label} | {LABELS[outcome]} | {why} | {tracking} |")

    server_id, day = document["server"]["id"], document["finished"][:10]
    lines = [f"**{_server_label(document)}** ({server_id}, {day})", ""]
    if rows:
        lines += [
            "| Scenario | Runtime | Outcome | Why | Tracking |",
            "|---|---|---|---|---|",
            *rows,
            "",
        ]
    else:
        lines += ["No failures: every scenario that ran passed on both runtimes.", ""]
    if unsupported:
        lines += [
            "Not offered by this server (unsupported optional features): "
            + ", ".join(f"`{s}`" for s in unsupported)
            + ".",
            "",
        ]
    if disagreements:
        lines += [
            "**The runtimes disagree on:** " + ", ".join(f"`{s}`" for s in disagreements) + ".",
            "",
        ]
    return lines


def render(documents: list[dict[str, Any]]) -> str:
    latest = latest_per_server(documents)
    lines = [BEGIN, ""]
    if not latest:
        lines += ["No conformance results have been published yet.", "", END]
        return "\n".join(lines)

    lines += [
        "| Server (BuildInfo) | Stack | Independent of both client stacks "
        "| Tested | Package | Level |",
        "|---|---|---|---|---|---|",
    ]
    for document in latest:
        server = document["server"]
        packages = sorted({run["package_version"] for run in document["runs"]})
        independent = (
            "yes"
            if server.get("independent")
            else f"no — {server.get('independenceNote', '')}".rstrip(" —")
        )
        lines.append(
            f"| {_server_label(document)} | {server['implementation']} | {independent} "
            f"| {document['finished'][:10]} | {', '.join(packages)} "
            f"| **{support_level(document)}** |"
        )

    lines += [
        "",
        "Passed of the scenarios that ran, per group. *unsupported* means the server "
        "itself does not offer the feature; *not configured* means the run did not "
        "exercise it.",
        "",
        "| Server | Runtime | " + " | ".join(GROUPS) + " |",
        "|---|---|" + "---|" * len(GROUPS),
    ]
    for document in latest:
        for run in sorted(document["runs"], key=lambda r: r["runtime"]):
            cells = [_cell(scenarios) for scenarios in _by_group(run).values()]
            lines.append(
                f"| {_server_label(document)} | {run['runtime']} {run.get('runtime_version', '')} "
                f"| " + " | ".join(cells) + " |"
            )

    lines += ["", "#### Findings", ""]
    for document in latest:
        lines += _findings(document)

    lines += [
        "Results: "
        + ", ".join(
            f"[`{d['server']['id']}-{d['finished'][:10]}.json`]"
            f"(../compatibility/results/{d['server']['id']}-{d['finished'][:10]}.json)"
            for d in latest
        )
        + ".",
        "",
        "<details><summary>The scenarios</summary>",
        "",
        "| Group | Scenario | What it checks |",
        "|---|---|---|",
        *(f"| {s.group} | `{s.id}` | {s.title} |" for s in SCENARIOS),
        "",
        "</details>",
        "",
        END,
    ]
    return "\n".join(lines)


def splice(doc_text: str, section: str) -> str:
    start = doc_text.find(BEGIN)
    end = doc_text.find(END)
    if start < 0 or end < 0 or end < start:
        raise ValueError(f"{DOC.name} has no generated-matrix markers")
    return doc_text[:start] + section + doc_text[end + len(END) :]


def current_section(doc_text: str) -> str:
    start = doc_text.find(BEGIN)
    end = doc_text.find(END)
    if start < 0 or end < 0:
        raise ValueError(f"{DOC.name} has no generated-matrix markers")
    return doc_text[start : end + len(END)]


def write(documents: list[dict[str, Any]], doc: Path = DOC) -> bool:
    """Rewrite the section; True if the file changed."""
    text = doc.read_text(encoding="utf-8")
    updated = splice(text, render(documents))
    if updated != text:
        doc.write_text(updated, encoding="utf-8")
        return True
    return False
