"""Generated by scripts/contract_codegen.py. Do not edit."""

# ruff: noqa
# fmt: off
from __future__ import annotations
from typing import Literal, TypeAlias, Union
from typing_extensions import Never, NotRequired, Required, TypedDict
JsonValue: TypeAlias = Union[None, bool, int, float, str, list["JsonValue"], dict[str, "JsonValue"]]
NodeValuesItemEngineeringObjectEuRangeObject = TypedDict('NodeValuesItemEngineeringObjectEuRangeObject', {
    'low': Required[float],
    'high': Required[float],
}, total=False)

NodeValuesItemEngineeringObjectInstrumentRangeObject = TypedDict('NodeValuesItemEngineeringObjectInstrumentRangeObject', {
    'low': Required[float],
    'high': Required[float],
}, total=False)

NodeValuesItemEngineeringObject = TypedDict('NodeValuesItemEngineeringObject', {
    'unit': Required[str | None],
    'unit_description': Required[str | None],
    'eu_range': Required[NodeValuesItemEngineeringObjectEuRangeObject | None],
    'instrument_range': Required[NodeValuesItemEngineeringObjectInstrumentRangeObject | None],
}, total=False)

NodeValuesItem = TypedDict('NodeValuesItem', {
    'node_id': Required[str],
    'value': Required[JsonValue],
    'data_type': Required[str | None],
    'status': Required[str],
    'source_timestamp': Required[str | None],
    'server_timestamp': Required[str | None],
    'engineering': Required[NodeValuesItemEngineeringObject | None],
}, total=False)

NodeValues: TypeAlias = list[NodeValuesItem]

NodeRefsNodesItem = TypedDict('NodeRefsNodesItem', {
    'node_id': Required[str],
    'browse_name': Required[str],
    'node_class': Required[str],
    'parent_node_id': Required[str],
    'data_type': Required[str | None],
    'value': Required[JsonValue],
    'description': Required[str | None],
    'type_definition': Required[str | None],
}, total=False)

NodeRefs = TypedDict('NodeRefs', {
    'nodes': Required[list[NodeRefsNodesItem]],
    'truncated': Required[bool],
    'inspected': Required[int],
}, total=False)

WriteResultsItem = TypedDict('WriteResultsItem', {
    'node_id': Required[str],
    'status': Required[str],
    'error': Required[str | None],
}, total=False)

WriteResults: TypeAlias = list[WriteResultsItem]

MethodResult = TypedDict('MethodResult', {
    'object_node_id': Required[str],
    'method_node_id': Required[str],
    'status': Required[str],
    'outputs': Required[list[JsonValue]],
}, total=False)

EventSubscription = TypedDict('EventSubscription', {
    'node_id': Required[str],
    'severity_min': Required[int],
    'buffer_size': Required[int],
    'replaced': Required[bool],
}, total=False)

Acknowledgement = TypedDict('Acknowledgement', {
    'event_id': Required[str],
    'condition_id': Required[str | None],
    'status': Required[str],
}, total=False)

HistoryRecordsItem = TypedDict('HistoryRecordsItem', {
    'value': Required[JsonValue],
    'timestamp': Required[str | None],
    'status': Required[str],
}, total=False)

HistoryRecords: TypeAlias = list[HistoryRecordsItem]

SubscriptionRecordsItem = TypedDict('SubscriptionRecordsItem', {
    'subscription_id': Required[str],
    'node_id': Required[str],
    'publishing_interval': Required[float],
    'sampling_interval': Required[float],
    'buffer_size': Required[float],
    'change_count': Required[float],
    'deadband_type': Required[str],
    'deadband_value': Required[float],
    'data_change_trigger': Required[str],
    'changes': Required[list[JsonValue]],
    'dropped': Required[int],
}, total=False)

SubscriptionRecords: TypeAlias = list[SubscriptionRecordsItem]

AlarmAction = TypedDict('AlarmAction', {
    'event_id': Required[str],
    'condition_id': Required[str | None],
    'action': Required[str],
    'status': Required[str],
}, total=False)

ServerStatusServerIdentity = TypedDict('ServerStatusServerIdentity', {
    'channel_secured': Required[bool],
    'server_authenticated': Required[bool],
    'authentication_method': Required[Literal['pin', 'none']],
    'control': Required[Literal['secured', 'INSECURE-OVERRIDE', 'UNVERIFIED-OVERRIDE', 'blocked']],
}, total=False)

ServerStatusBuildInfoObject = TypedDict('ServerStatusBuildInfoObject', {

}, total=False)

ServerStatusDiagnosticsObject = TypedDict('ServerStatusDiagnosticsObject', {
    'server_view_count': Required[float],
    'current_session_count': Required[float],
    'cumulated_session_count': Required[float],
    'security_rejected_session_count': Required[float],
    'rejected_session_count': Required[float],
    'session_timeout_count': Required[float],
    'session_abort_count': Required[float],
    'current_subscription_count': Required[float],
    'cumulated_subscription_count': Required[float],
    'publishing_interval_count': Required[float],
    'security_rejected_requests_count': Required[float],
    'rejected_requests_count': Required[float],
}, total=False)

ServerStatusCapabilitiesSupport = TypedDict('ServerStatusCapabilitiesSupport', {
    'history': Required[Literal['supported', 'not_supported', 'unknown']],
    'historyEvents': Required[Literal['supported', 'not_supported', 'unknown']],
    'aggregate': Required[Literal['supported', 'not_supported', 'unknown']],
}, total=False)

ServerStatusCapabilities = TypedDict('ServerStatusCapabilities', {
    'session_generation': Required[int | None],
    'checked_at': Required[str | None],
    'support': Required[ServerStatusCapabilitiesSupport],
    'aggregate_functions': Required[list[JsonValue]],
}, total=False)

ServerStatus = TypedDict('ServerStatus', {
    'connected': Required[bool],
    'endpoint_url': Required[str],
    'security': Required[str],
    'server_identity': Required[ServerStatusServerIdentity],
    'server_state': Required[str | None],
    'current_time': Required[str | None],
    'start_time': Required[str | None],
    'build_info': Required[ServerStatusBuildInfoObject | None],
    'diagnostics': Required[ServerStatusDiagnosticsObject | None],
    'namespaces': Required[list[JsonValue]],
    'error': Required[str | None],
    'capabilities': Required[ServerStatusCapabilities],
}, total=False)

EventRecordsItem = TypedDict('EventRecordsItem', {
    'event_id': Required[str | None],
    'event_type': Required[str | None],
    'source_node': Required[str | None],
    'source_name': Required[str | None],
    'time': Required[str | None],
    'message': Required[str | None],
    'severity': Required[float | None],
    'condition_id': Required[str | None],
    'condition_name': Required[str | None],
    'active': Required[bool | None],
    'acked': Required[bool | None],
    'retain': Required[bool | None],
}, total=False)

EventRecords: TypeAlias = list[EventRecordsItem]

CompletenessContinuationObject = TypedDict('CompletenessContinuationObject', {

}, total=False)

Completeness = TypedDict('Completeness', {
    'complete': Required[bool],
    'reasons': Required[list[Literal['requestLimit', 'contractLimit', 'serverLimit', 'bufferOverflow', 'unbrowsable']]],
    'returned': Required[int],
    'truncated': Required[bool],
    'limit': Required[int | None],
    'dropped': Required[int],
    'remaining': Required[bool | None],
    'continuation': Required[CompletenessContinuationObject | None],
}, total=False)

ReadOpcuaNodesInput = TypedDict('ReadOpcuaNodesInput', {
    'node_ids': Required[list[str]],
}, total=False)

ReadOpcuaNodesResult = TypedDict('ReadOpcuaNodesResult', {'result': NodeValues})

BrowseOpcuaNodesInput = TypedDict('BrowseOpcuaNodesInput', {
    'node_id': NotRequired[str | None],
    'browse_path': NotRequired[str | None],
    'depth': NotRequired[int | None],
    'node_class': NotRequired[Literal['Object', 'Variable', 'Method', 'ObjectType', 'VariableType', 'ReferenceType', 'DataType', 'View', None]],
    'name_filter': NotRequired[str | None],
    'include_values': NotRequired[bool | None],
    'max_nodes': NotRequired[int | None],
}, total=False)

BrowseOpcuaNodesResult = TypedDict('BrowseOpcuaNodesResult', {'result': NodeRefs, 'completeness': Completeness})

ReadOpcuaHistoryInput = TypedDict('ReadOpcuaHistoryInput', {
    'node_id': Required[str],
    'start_time': NotRequired[str | None],
    'end_time': NotRequired[str | None],
    'num_values': NotRequired[int | None],
    'aggregate_function': NotRequired[str | None],
    'processing_interval': NotRequired[float | None],
}, total=False)

ReadOpcuaHistoryResult = TypedDict('ReadOpcuaHistoryResult', {'result': HistoryRecords, 'completeness': Completeness})

ReadEventHistoryInput = TypedDict('ReadEventHistoryInput', {
    'node_id': NotRequired[str | None],
    'start_time': NotRequired[str | None],
    'end_time': NotRequired[str | None],
    'num_values': NotRequired[int | None],
    'severity_min': NotRequired[int | None],
}, total=False)

ReadEventHistoryResult = TypedDict('ReadEventHistoryResult', {'result': EventRecords, 'completeness': Completeness})

GetServerStatusInput = TypedDict('GetServerStatusInput', {

}, total=False)

GetServerStatusResult = TypedDict('GetServerStatusResult', {'result': ServerStatus})

ListSubscriptionsInput = TypedDict('ListSubscriptionsInput', {

}, total=False)

ListSubscriptionsResult = TypedDict('ListSubscriptionsResult', {'result': SubscriptionRecords, 'completeness': Completeness})

ListActiveAlarmsInput = TypedDict('ListActiveAlarmsInput', {
    'node_id': NotRequired[str | None],
    'timeout_seconds': NotRequired[float | None],
}, total=False)

ListActiveAlarmsResult = TypedDict('ListActiveAlarmsResult', {'result': EventRecords})

WriteOpcuaNodesInputNodesItemValueObject = TypedDict('WriteOpcuaNodesInputNodesItemValueObject', {

}, total=False)

WriteOpcuaNodesInputNodesItem = TypedDict('WriteOpcuaNodesInputNodesItem', {
    'node_id': Required[str],
    'value': Required[bool | float | str | WriteOpcuaNodesInputNodesItemValueObject | list[JsonValue]],
    'data_type': NotRequired[Literal['Boolean', 'SByte', 'Byte', 'Int16', 'UInt16', 'Int32', 'UInt32', 'Int64', 'UInt64', 'Float', 'Double', 'String', 'DateTime', 'Guid', 'ByteString', None]],
}, total=False)

WriteOpcuaNodesInput = TypedDict('WriteOpcuaNodesInput', {
    'nodes': Required[list[WriteOpcuaNodesInputNodesItem]],
}, total=False)

WriteOpcuaNodesResult = TypedDict('WriteOpcuaNodesResult', {'result': WriteResults})

CallOpcuaMethodInput = TypedDict('CallOpcuaMethodInput', {
    'object_node_id': Required[str],
    'method_node_id': Required[str],
    'arguments': NotRequired[list[JsonValue] | None],
}, total=False)

CallOpcuaMethodResult = TypedDict('CallOpcuaMethodResult', {'result': MethodResult})

SubscribeOpcuaNodesInput = TypedDict('SubscribeOpcuaNodesInput', {
    'node_ids': Required[list[str]],
    'publishing_interval': NotRequired[float | None],
    'sampling_interval': NotRequired[float | None],
    'buffer_size': NotRequired[int | None],
    'deadband_type': NotRequired[Literal['none', 'absolute', 'percent', None]],
    'deadband_value': NotRequired[float | None],
    'data_change_trigger': NotRequired[Literal['status', 'statusValue', 'statusValueTimestamp', None]],
}, total=False)

SubscribeOpcuaNodesResult = TypedDict('SubscribeOpcuaNodesResult', {'result': SubscriptionRecords, 'completeness': Completeness})

UnsubscribeOpcuaNodesInput = TypedDict('UnsubscribeOpcuaNodesInput', {
    'subscription_ids': Required[list[str]],
}, total=False)

UnsubscribeOpcuaNodesResult = TypedDict('UnsubscribeOpcuaNodesResult', {'result': SubscriptionRecords, 'completeness': Completeness})

SubscribeEventsInput = TypedDict('SubscribeEventsInput', {
    'node_id': NotRequired[str | None],
    'severity_min': NotRequired[int | None],
    'buffer_size': NotRequired[int | None],
}, total=False)

SubscribeEventsResult = TypedDict('SubscribeEventsResult', {'result': EventSubscription})

ReadEventsInput = TypedDict('ReadEventsInput', {
    'node_id': NotRequired[str | None],
    'limit': NotRequired[int | None],
}, total=False)

ReadEventsResult = TypedDict('ReadEventsResult', {'result': EventRecords, 'completeness': Completeness})

AcknowledgeAlarmInput = TypedDict('AcknowledgeAlarmInput', {
    'event_id': Required[str],
    'comment': NotRequired[str | None],
    'condition_id': NotRequired[str | None],
}, total=False)

AcknowledgeAlarmResult = TypedDict('AcknowledgeAlarmResult', {'result': Acknowledgement})

ActOnAlarmInput = TypedDict('ActOnAlarmInput', {
    'event_id': Required[str],
    'action': Required[Literal['acknowledge', 'confirm', 'comment', 'shelve', 'shelveFor', 'unshelve']],
    'comment': NotRequired[str | None],
    'shelve_duration_ms': NotRequired[float | None],
    'condition_id': NotRequired[str | None],
}, total=False)

ActOnAlarmResult = TypedDict('ActOnAlarmResult', {'result': AlarmAction})

SCHEMA_KEYWORDS = ('$comment', '$schema', 'additionalProperties', 'const', 'description', 'enum', 'exclusiveMaximum', 'exclusiveMinimum', 'items', 'maxItems', 'maxLength', 'maximum', 'minItems', 'minLength', 'minimum', 'multipleOf', 'pattern', 'properties', 'required', 'title', 'type', 'uniqueItems')
TOOL_NAMES = ('read_opcua_nodes', 'browse_opcua_nodes', 'read_opcua_history', 'read_event_history', 'get_server_status', 'list_subscriptions', 'list_active_alarms', 'write_opcua_nodes', 'call_opcua_method', 'subscribe_opcua_nodes', 'unsubscribe_opcua_nodes', 'subscribe_events', 'read_events', 'acknowledge_alarm', 'act_on_alarm')
ToolName: TypeAlias = Literal['read_opcua_nodes', 'browse_opcua_nodes', 'read_opcua_history', 'read_event_history', 'get_server_status', 'list_subscriptions', 'list_active_alarms', 'write_opcua_nodes', 'call_opcua_method', 'subscribe_opcua_nodes', 'unsubscribe_opcua_nodes', 'subscribe_events', 'read_events', 'acknowledge_alarm', 'act_on_alarm']
TOOL_INPUT_TYPES = {'read_opcua_nodes': ReadOpcuaNodesInput, 'browse_opcua_nodes': BrowseOpcuaNodesInput, 'read_opcua_history': ReadOpcuaHistoryInput, 'read_event_history': ReadEventHistoryInput, 'get_server_status': GetServerStatusInput, 'list_subscriptions': ListSubscriptionsInput, 'list_active_alarms': ListActiveAlarmsInput, 'write_opcua_nodes': WriteOpcuaNodesInput, 'call_opcua_method': CallOpcuaMethodInput, 'subscribe_opcua_nodes': SubscribeOpcuaNodesInput, 'unsubscribe_opcua_nodes': UnsubscribeOpcuaNodesInput, 'subscribe_events': SubscribeEventsInput, 'read_events': ReadEventsInput, 'acknowledge_alarm': AcknowledgeAlarmInput, 'act_on_alarm': ActOnAlarmInput}
TOOL_RESULT_TYPES = {'read_opcua_nodes': ReadOpcuaNodesResult, 'browse_opcua_nodes': BrowseOpcuaNodesResult, 'read_opcua_history': ReadOpcuaHistoryResult, 'read_event_history': ReadEventHistoryResult, 'get_server_status': GetServerStatusResult, 'list_subscriptions': ListSubscriptionsResult, 'list_active_alarms': ListActiveAlarmsResult, 'write_opcua_nodes': WriteOpcuaNodesResult, 'call_opcua_method': CallOpcuaMethodResult, 'subscribe_opcua_nodes': SubscribeOpcuaNodesResult, 'unsubscribe_opcua_nodes': UnsubscribeOpcuaNodesResult, 'subscribe_events': SubscribeEventsResult, 'read_events': ReadEventsResult, 'acknowledge_alarm': AcknowledgeAlarmResult, 'act_on_alarm': ActOnAlarmResult}
