"""Validate the contract and reproducibly generate both runtimes' static surface."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
DRAFT = "https://json-schema.org/draft/2020-12/schema"
# This is the supported authoring profile, not a handwritten validator.
# Each keyword's runtime semantics belong to Ajv/jsonschema. Keep type generation
# deliberately finite: unrepresentable schema features must fail CI explicitly.
KEYWORDS = set(
    json.loads((ROOT / "contract/schema-profile.json").read_text(encoding="utf-8"))["keywords"]
)


def check_schema(schema):
    if isinstance(schema, bool):
        return
    unknown = set(schema) - KEYWORDS
    if unknown:
        raise ValueError(f"Unsupported schema keywords: {sorted(unknown)}")
    for value in schema.get("properties", {}).values():
        check_schema(value)
    for key in ("items", "additionalProperties"):
        if isinstance(schema.get(key), (dict, bool)):
            check_schema(schema[key])
    Draft202012Validator.check_schema(schema)


def name(value):
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_-]", value))


class Types:
    def __init__(self):
        self.python = []

    def pair(self, schema, symbol):
        if schema is True or schema == {}:
            return "JsonValue", "JsonValue"
        if schema is False:
            return "never", "Never"
        if "const" in schema or "enum" in schema:
            values = [schema["const"]] if "const" in schema else schema["enum"]
            return " | ".join(json.dumps(v) for v in values), "Literal[" + ", ".join(
                repr(v) for v in values
            ) + "]"
        types = schema.get("type")
        if isinstance(types, list):
            parts = [self.pair({**schema, "type": t}, symbol + name(t)) for t in types]
            return " | ".join(t[0] for t in parts), " | ".join(t[1] for t in parts)
        if types == "array":
            ts, py = self.pair(schema.get("items", {}), symbol + "Item")
            return f"Array<{ts}>", f"list[{py}]"
        if types == "object":
            props = schema.get("properties", {})
            required = set(schema.get("required", []))
            members = []
            lines = []
            for key, sub in props.items():
                ts, py = self.pair(sub, symbol + name(key))
                members.append(json.dumps(key) + ("" if key in required else "?") + ": " + ts)
                lines.append(
                    f"    {key!r}: {'Required' if key in required else 'NotRequired'}[{py}],"
                )
            if schema.get("additionalProperties") is not False:
                ts, _ = self.pair(schema.get("additionalProperties", {}), symbol + "Extra")
                # Known fields must also satisfy the index signature in TS.
                members.append("[key: string]: JsonValue")
            self.python.append(
                f"{symbol} = TypedDict({symbol!r}, {{\n" + "\n".join(lines) + "\n}, total=False)\n"
            )
            return "{ " + "; ".join(members) + " }", symbol
        return {
            "string": ("string", "str"),
            "integer": ("number", "int"),
            "number": ("number", "float"),
            "boolean": ("boolean", "bool"),
            "null": ("null", "None"),
            None: ("JsonValue", "JsonValue"),
        }[types]


def render(contract):
    gen = Types()
    ts = [
        "// Generated by scripts/contract_codegen.py. Do not edit.",
        "export type JsonValue = null | boolean | number | string | JsonValue[] "
        "| { [key: string]: JsonValue };",
    ]
    inputs, results = {}, {}
    for key, schema in contract["resultShapes"].items():
        if key.startswith("$"):
            continue
        check_schema(schema)
        symbol = name(key)
        t, p = gen.pair(schema, symbol)
        ts.append(f"export type {symbol} = {t};")
        if p != symbol:
            gen.python.append(f"{symbol}: TypeAlias = {p}\n")
    check_schema(contract["completeness"]["schema"])
    t, p = gen.pair(contract["completeness"]["schema"], "Completeness")
    ts.append(f"export type Completeness = {t};")
    for tool in contract["tools"]:
        check_schema(tool["inputSchema"])
        symbol = name(tool["name"]) + "Input"
        t, p = gen.pair(tool["inputSchema"], symbol)
        ts.append(f"export type {symbol} = {t};")
        inputs[tool["name"]] = symbol
        shape = name(tool["resultShape"]) if tool.get("resultShape") else "JsonValue"
        result_symbol = name(tool["name"]) + "Result"
        envelope = {
            "type": "object",
            "properties": {"result": {}},
            "required": ["result"],
            "additionalProperties": False,
        }
        if tool.get("reportsCompleteness"):
            envelope["properties"]["completeness"] = contract["completeness"]["schema"]
            envelope["required"].append("completeness")
        fields = f"result: {shape}" + (
            "; completeness: Completeness" if tool.get("reportsCompleteness") else ""
        )
        ts.append(f"export type {result_symbol} = {{ {fields} }};")
        gen.python.append(
            f"{result_symbol} = TypedDict({result_symbol!r}, {{'result': {shape}"
            + (", 'completeness': Completeness" if tool.get("reportsCompleteness") else "")
            + "})\n"
        )
        results[tool["name"]] = result_symbol
    ts.extend(
        [
            "export const TOOL_NAMES = " + json.dumps(list(inputs)) + " as const;",
            "export type ToolName = typeof TOOL_NAMES[number];",
            "export interface ToolInputs { "
            + "; ".join(json.dumps(k) + ": " + v for k, v in inputs.items())
            + " }",
            "export interface ToolResults { "
            + "; ".join(json.dumps(k) + ": " + v for k, v in results.items())
            + " }",
            "export type ToolHandlers = { [K in ToolName]: "
            "(input: ToolInputs[K]) => Promise<ToolResults[K]> };",
        ]
    )
    py = [
        '"""Generated by scripts/contract_codegen.py. Do not edit."""',
        "",
        "# ruff: noqa",
        "# fmt: off",
        "from __future__ import annotations",
        "from typing import Literal, TypeAlias, Union",
        "from typing_extensions import Never, NotRequired, Required, TypedDict",
        "JsonValue: TypeAlias = Union[None, bool, int, float, str, "
        'list["JsonValue"], dict[str, "JsonValue"]]',
        *gen.python,
        "SCHEMA_KEYWORDS = " + repr(tuple(sorted(KEYWORDS))),
        "TOOL_NAMES = " + repr(tuple(inputs)),
        "ToolName: TypeAlias = Literal[" + ", ".join(repr(k) for k in inputs) + "]",
        "TOOL_INPUT_TYPES = {" + ", ".join(repr(k) + ": " + v for k, v in inputs.items()) + "}",
        "TOOL_RESULT_TYPES = {" + ", ".join(repr(k) + ": " + v for k, v in results.items()) + "}",
    ]
    schemas = {
        "$schema": DRAFT,
        "$defs": {
            **{name(k): v for k, v in contract["resultShapes"].items() if not k.startswith("$")},
            "Completeness": contract["completeness"]["schema"],
            **{name(t["name"]) + "Input": t["inputSchema"] for t in contract["tools"]},
        },
    }
    return {
        ROOT / "packages/server-node/src/generated/contract-types.ts": "\n".join(ts) + "\n",
        ROOT / "packages/server-python/src/opcua_mcp_server/generated_contract.py": "\n".join(py)
        + "\n",
        ROOT / "contract/schemas.json": json.dumps(schemas, indent=2, ensure_ascii=False) + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = json.loads((ROOT / "contract/tools.json").read_text(encoding="utf-8"))
    meta = json.loads((ROOT / "contract/contract.schema.json").read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(meta)
    Draft202012Validator(meta).validate(contract)
    for path, content in render(contract).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated contract drift: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
